### ISSUE TITLE
LOOPY cant connect while using Touch Portal

### ISSUE THREAD

**Issue by GrabaGra** [loopy750/SRT-Stats-Monitor#23]
Im using Touch Portal (which also connects by OBS websocket) so my moderators can change things during my IRL streams.
But while using it - I can't connect to LOOPY - it just gives me test number 6 fail.

If I restart the computer - everything is fine. If I turn on Touch Portal - I can't get LOOPY to start (and if I open TP after LOOPY, it just stops working).

**Comment by loopy750** [comment]
I've never used this before, so I downloaded it for the first time. I installed it on Windows 11, and then on Android. At first try I was unable to reproduce any errors. SRT Monitor is working side-by-side with Touch Portal without an issue. I can use my phone to change settings in OBS and SRT Monitor is doing its thing. Is there anything I can try to reproduce it?

You should see two connections in WebSocket Settings if everything is working fine.

![Image1](https://github.com/loopy750/SRT-Stats-Monitor/assets/35911135/2c9f742d-3936-4002-9110-1c2681acbfc3)
![Image2](https://github.com/loopy750/SRT-Stats-Monitor/assets/35911135/dafb768f-ea85-4c91-a399-437198dab4fc)

**Comment by GrabaGra** [comment]
Well it's weird, because even thou LOOPY is working and changing scenes - I don't see it in OBS Websocket.
![3PDGvYly3c](https://github.com/loopy750/SRT-Stats-Monitor/assets/133253121/89c6d567-f1fe-4bbf-ae03-ba2664ec30ac)

Everything is fine and working, but after turning on Touch Portal I can't connect to LOOPY. Password and IP are the same and even without authentication, it doesn't work.
Also - I can see Touch Portal on the OBS websocket list.

I've also had 2 OBS installed on my PC, but one is uninstalled. But maybe some files stayed on the drive and it's making those errors? It's been a long time since the format, so maybe I will try the clean install.

**Comment by GrabaGra** [comment]
I did a format and still got the same issue :/  LOOPY just can't connect if Touch Portal is working.

BUT:
If I turn on LOOPY first, and then Touch Portal - it seems to work without any issues.

**Comment by loopy750** [comment]
Interesting. Well, I always recommend not changing most default settings unless there's a specific reason. That's why I was unable to reproduce it.

Although that said, I still can't reproduce it even when replacing `127.0.0.1` with `localhost`, but generally no two networks are exactly the same, so I'm not sure what's happening, if ipv6 has something to do with it, or who knows.

It also doesn't help that for whatever reason, WebSocket isn't displaying your connections. If I use `localhost`, it resolves to ipv6, as shown in the images, vs ipv4.

![Image1](https://github.com/loopy750/SRT-Stats-Monitor/assets/35911135/f708f71b-f95c-4c0d-b6be-4a582e290b24)
![Image2](https://github.com/loopy750/SRT-Stats-Monitor/assets/35911135/44c01ee7-b260-49dc-bd9e-b4efab846df9)


But, glad to see you got it sorted, troubleshooting networking issues can be a pain in the ass to say the least.
