### ISSUE TITLE
Gstreamer SRT source in OBS

### ISSUE THREAD

**Issue by RockNRollGeek** [loopy750/SRT-Stats-Monitor#5]
Hi,

I've tried to use Media Source for SRT listeners in OBS to no avail. The connection from larix is fine, but OBS just displays black video with the audio. However SRT listeners work just fine both in vmix and in obs when using obs-gstreamer plugin/gstreamer source in OBS. When I do this though, SRT stats monitor boots up fine, but thinks the stream has failed. Is there any way to have it recognize gstreamer sources in OBS instead of just OBS Media Source sources?

Thanks!
-C

**Comment by loopy750** [comment]
Hi,

I've never used gstreamer, and I have no idea how to setup everything. I installed the program as well as the obs plugin but it appears to be quite a learning curve to get it running. SRT monitor basically reads the Media Source timestamp. From what you've described it seems possible with gstreamer the time remains at 0 seconds, but I can't confirm as I understand little about it.

**Comment by RockNRollGeek** [comment]
Not sure if this helps, but quick and easy way to get gstreamer and obs going are:   
  
1: download and install the latest gstreamer minGW 64 bit windows build
  
2: make sure gstreamers bin directory (likely C:\gstreamer\bin )is added to the system PATH in windows
  
3: install the obs gstreamer plugin - if the gstreamer bin folder is in the system path directory then the plug-in should load (can be verified in obs log)
  
4: add your srt listener as a gstreamer source - I used this thread/post for reference:   https://obsproject.com/forum/threads/receive-srt-stream-within-obs.129698/post-535914
  

  
Hopefully that can at least help get it running in the event you’re trying to play with it and the plugin’s not loading or something
  
  
  
>   
>
>

**Comment by loopy750** [comment]
Yep the plugin wasn't loading, but your steps helped me get it going.

Unfortunately it doesn't seem possible at this stage. Pulling a timestamp is possible from Media Source, VLC Video Source, but not GStreamer Source. All I'm getting is a 'null' response.

I mentioned it to the OBS Websocket dev and his response was **_"the developer of the source should implement the_ `.media_get_time` _callback"_**. I suppose you could raise an issue with the GStreamer dev and see what he thinks, as otherwise I don't know any way for OBS Websocket (and therefore my program) to know the current state of the source i.e. Playing, Paused, current duration, etc.

**Comment by loopy750** [comment]
Received an email about a new version, but it does not address this. Seeing as it's beyond my control, I'll close this issue, but can be reopened if need be.

**Comment by loopy750** [comment]
FWIW received another email about a new version, and it now works, since v0.4.0.

Those settings don't want to work but I got it working with: 
`srtsrc uri="srt://:49990?mode=listener" ! tsdemux ! h264parse ! avdec_h264  ! video.`
